Feature to reset password
DataKrewTech/MADS-IoT-Explorer pull request #118
Opened 2020-11-23 11:03 UTC by Ayoush

Feature to reset password

How:-
1. User will click forgot password link which will trigger one mail to
   user containing the reset link.
2. On clicking the link user will be redirected to a page where he will
   reset the password by entering the new one.

2020-12-28 10:19 UTC, arjun289 requested changes
- Please remove commented out code.
- Do not seed data when you are testing failure because of authorization related issues. It will only slow down the tests
- Also, seed in the setup block of `describe` so that you don't have to write it again and again in the tests.
- The retry for elastic search insert doesn't appear to be implemented properly.
- Seems while searching and indexing with elastic search, a DB query is being run to load the data for every entity found. Why don't you load all the data in just one query for all the entities found.
- While seeding multiple entities in elastic search instead of inserting just three entities take input from user and use Enum or comprehensions to iterate and seed.

2020-12-28 10:19 UTC, arjun289 commented on apps/acqdat_api/lib/acqdat_api_web/controllers/role-management/invitation_controller.ex
> +        |> send_error(404, "User already exists with this email address")
How are you coming to this conclusion. I couldn't find a reasonable logic to this?

2020-12-28 10:19 UTC, arjun289 commented on apps/acqdat_api/test/acqdat_api_web/controllers/elasticsearch/asset_controller_test.exs
> +      :timer.sleep(2500)
No need to seed here as you are testing failure due to bad header.

2020-12-28 10:19 UTC, arjun289 commented on apps/acqdat_api/test/acqdat_api_web/controllers/elasticsearch/asset_controller_test.exs
> +      :timer.sleep(2500)
No need to seed here.

2020-12-29 07:35 UTC, Ayoush commented on apps/acqdat_api/lib/acqdat_api_web/controllers/iot-manager/gateway_controller.ex
> +  # end
done

2020-12-29 07:35 UTC, Ayoush commented on apps/acqdat_api/lib/acqdat_api_web/controllers/entity-management/project_controller.ex
> +
done

2021-01-03 21:50 UTC, merged