Feature/role manager
DataKrewTech/MADS-IoT-Explorer pull request #126
Opened 2021-01-08 10:06 UTC by Ayoush

Added method to extract all the routes
API to show those available routes
APIs to add user group 
APIs to add policy
Altered invitation logic

2021-01-18 13:30 UTC, arjun289 requested changes

2021-01-20 11:48 UTC, Ayoush commented on apps/acqdat_api/lib/acqdat_api/api_access/user_group.ex
> +    params = Map.put_new(params, :user_ids, [])
done

2021-01-20 12:14 UTC, Ayoush commented on apps/acqdat_api/lib/acqdat_api/api_access/user_group.ex
> +    params = Map.put_new(params, :user_ids, [])
it is there as i kept it for future use as suggested by you. I am doing this just for ensuring other wise this check is also there in validators also.

2021-01-20 12:15 UTC, Ayoush commented on apps/acqdat_api/lib/acqdat_api/entity-management/organisation.ex
> +      nil -> verify_organisation(OrgModel.create(params))
Done, i made it compulsory in validator of organisation so this code will not be reached without providing user details

2021-01-20 12:17 UTC, Ayoush commented on apps/acqdat_api/lib/acqdat_api/extract_routes.ex
> +  #  }
Done

2021-01-20 12:18 UTC, Ayoush commented on apps/acqdat_api/lib/acqdat_api/extract_routes.ex
> +  def extract_routes() do
I am using this function in ExtractedRoutesController

2021-01-20 13:10 UTC, Ayoush commented on apps/acqdat_api/lib/acqdat_api_web/auth_pipeline/api_access_auth.ex
> +          end)
done

2021-01-27 04:21 UTC, Ayoush commented on apps/acqdat_api/lib/acqdat_api_web/auth_pipeline/api_access_auth.ex
> +              acc ++ [policies.policy]
Done

2021-01-27 09:04 UTC, arjun289 approved these changes

2021-01-27 09:16 UTC, merged