Fix (most) warnings
DataKrewTech/MADS-IoT-Explorer pull request #193
Opened 2021-06-18 11:00 UTC by ChiragCD

# Why?

The "mix compile --force" command generates a number of warnings. Many of them are in dependencies, and cannot be resolved here. This merge handles most of the remaining warnings.

## Significant Changes

- Add local (umbrella) and general dependencies to mix files
- Set core/schema functions (add_uuid, add_slug, random_string) as overridable, as specific implementations are provided for these in some files. These implementations were previously ignored, they will now be used. May cause changes in dashboard management and tool management, may require testing.
- In pivot_tables.ex, private function pivot_values_col_data, set acc to accumulate all rows, rather than just the last row from rows_data.

## Minor Changes

- Convert variables to anonymous variables where they are not used
- Comment out import/use/alias statements where they are not used
- Reorder functions to place those with same name and arity together

2021-06-25 10:08 UTC, blackode requested changes

2021-06-27 15:39 UTC, ChiragCD commented on apps/acqdat_api/lib/acqdat_api/alerts/alert_filter_listing.ex
>      end)
Implemented

2021-06-27 15:40 UTC, ChiragCD commented on apps/acqdat_api/lib/acqdat_api/alerts/alert_filter_listing.ex
>      end)
Implemented

2021-06-27 15:40 UTC, ChiragCD commented on apps/acqdat_api/lib/acqdat_api/alerts/policy.ex
>      end)
Implemented

2021-06-27 15:40 UTC, ChiragCD commented on apps/acqdat_api/lib/acqdat_api/api_access/user_group.ex
> +    verify_group(UserGroup.normal_update(group, params))
Implemented

2021-06-27 15:40 UTC, ChiragCD commented on apps/acqdat_api/lib/acqdat_api/data_cruncher/task.ex
> +    verify_task(TaskModel.get(id), params)
Possible consistency issues?

2021-06-27 15:41 UTC, ChiragCD commented on apps/acqdat_api/lib/acqdat_api/data_insights/fact_tables.ex
> +    _output =
Implemented

2021-06-27 15:41 UTC, ChiragCD commented on apps/acqdat_api/lib/acqdat_api/data_insights/fact_tables.ex
> +    _output =
Implemented

2021-06-27 15:41 UTC, ChiragCD commented on apps/acqdat_api/lib/acqdat_api/data_insights/fact_tables.ex
> +    _output =
Implemented

2021-06-27 15:41 UTC, ChiragCD commented on apps/acqdat_api/lib/acqdat_api_web/controllers/entity-management/project_controller.ex
> +    _params =
Implemented

2021-06-27 15:41 UTC, ChiragCD commented on apps/acqdat_core/lib/acqdat_core/data_cruncher/domain/task.ex
>          acc ++ [gen_edge(edge)]
Implemented

2021-06-27 15:42 UTC, ChiragCD commented on apps/acqdat_core/priv/repo/seed/data_insights/topology.ex
> +        sensor_id: sensor.id, project_id: sensor.project_id, org_id: sensor.org_id,
Implemented

2021-06-27 15:42 UTC, ChiragCD commented on apps/acqdat_core/priv/repo/seed/data_insights/topology.ex
> +        sensor_id: sensor.id, project_id: sensor.project_id, org_id: sensor.org_id,
Implemented

2021-06-27 15:42 UTC, ChiragCD commented on apps/acqdat_core/priv/repo/seed/data_insights/topology.ex
>      end)
Implemented

2021-07-30 10:16 UTC, ChiragCD commented
Subsumed under PR 220, branch fixes/warnings

2021-07-30 10:16 UTC, closed without merging