Feature/entity management alert
DataKrewTech/MADS-IoT-Explorer pull request #247
Opened 2021-10-20 11:45 UTC by Ayoush

- `_Problem Statement_` :- To provide support of alert in entity management system.

2021-12-22 13:39 UTC, arjun289 requested changes

2021-12-22 13:39 UTC, arjun289 commented on apps/acqdat_core/lib/acqdat_core/entity-management/model/grouping.ex
> +  All the alerts which are generated from the same entity(sensor, gateway, asset)
Why have you commented out all the code in this module.

2021-12-29 07:38 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api_web/router.ex
> +        # get "/alert_status", AlertFilterListingController, :alert_status_listing
done

2021-12-29 07:38 UTC, BandanaPandey commented on apps/acqdat_core/lib/acqdat_core/entity-management/alert_creations/alert_creation.ex
> +             password: "guest"
done

2021-12-29 07:38 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api/entity-management/alert_rules.ex
> +  def verify_alert_rules({:error, message}) do
done

2022-01-11 03:49 UTC, Ayoush commented on apps/acqdat_core/lib/acqdat_core/iot-manager/data_handler/data_parser.ex
> +    AMQP.Connection.close(connection)
Connection should not be closed

2022-01-12 12:23 UTC, merged