[MIP-256] Reports - Template API
DataKrewTech/MADS-IoT-Explorer pull request #248
Opened 2021-10-28 22:10 UTC by sandeshsoni

Schema, Model, Validation, API for Template
Embedded schemas for Template-pages and elements
CRUD
Better error message for invalid IDs
Better error message for uniq constraint name
some code cleanup

2022-01-04 09:19 UTC, sandeshsoni commented on apps/acqdat_api/lib/acqdat_api/reports/template_instance.ex
> +  def get_all(_data) do
Hi @BandanaPandey .
Because there would be params filtering in future. params like offset, etc.
So I did not use defdelegate here. Other places used defdelegate.

2022-01-12 04:23 UTC, niteshcode4u commented
Hello @sandeshsoni 
Before reviewing I would request please do the followings

1. Would you mind adding a Jira ticket
2. Can you please add unit test cases for at least 4 controllers
3. As per the defined code [standard](https://datakrew.atlassian.net/wiki/spaces/MD/pages/124977153/Elixir+Style+Guide-+MADS) single piping is not recommended but in these changes, I have seen a lot. would you mind removing that in the first place?

2022-01-14 07:43 UTC, niteshcode4u requested changes
@dhavalarora Please do some cosmetic changes.

2022-01-14 07:43 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api_web/controllers/reports/template_controller.ex
> +    end
```
with nil <- conn.status,
  changeset <- verify_update_params(params), 
  {:extract, {:ok, data}} <- extract_changeset_data(changeset),
  {:update, {:ok, template}} <- {:update, Templates.update(conn.assigns.template, data)} do
    
    conn
    |> put_status(200)
    |> render("show.json", %{template: template})
else
  404 ->
    send_error(conn, 404, TemplateErrorHelper.error_message(:resource_not_found))

  401 ->
    send_error(conn, 401, TemplateErrorHelper.error_message(:unauthorized))
    
  {:extract, {:error, error}} ->
    send_error(conn, 400, error)

  {:update, {:error, message}} ->
    send_error(conn, 400, message.error)
end
```

2022-01-14 07:43 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api_web/controllers/reports/template_controller.ex
> +    end
Please follow the same structure suggested above

2022-01-14 07:43 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api_web/controllers/reports/widget_mould_controller.ex
> +        |> Map.put(:data_prop, HighCharts.parse_properties(conn.assigns.widget.data_settings))
```
conn.assigns.widget
|> Map.put(:visual_prop, HighCharts.parse_properties(conn.assigns.widget.visual_settings))
|> Map.put(:data_prop, HighCharts.parse_properties(conn.assigns.widget.data_settings))
```

2022-01-14 07:43 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api_web/plugs/load_report_widget_instance.ex
> +            |> put_status(404)
please remove single piping `put_status(conn, 404)`

2022-01-14 07:43 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api_web/plugs/load_report_widget_instance.ex
> +        |> put_status(404)
please remove single piping

2022-01-14 07:43 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api_web/plugs/load_template.ex
> +            |> put_status(404)
please remove single piping

2022-01-14 07:43 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api_web/plugs/load_template.ex
> +        |> put_status(404)
please remove single piping

2022-01-14 07:43 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api_web/plugs/load_template_instance.ex
> +            |> put_status(404)
please remove single piping

2022-01-14 07:43 UTC, niteshcode4u commented on apps/acqdat_core/lib/acqdat_core/reports/model/template.ex
> +    |> Repo.all()
please remove single piping

2022-01-14 07:43 UTC, niteshcode4u commented on apps/acqdat_core/lib/acqdat_core/reports/model/template_instance.ex
> +    |> Repo.all()
please remove single piping

2022-01-14 07:46 UTC, niteshcode4u commented
Jira:
https://datakrew.atlassian.net/browse/MIP-185
https://datakrew.atlassian.net/browse/MIP-256

2022-01-19 06:37 UTC, niteshcode4u requested changes

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_controller_test.exs
> +      assert response["name"] == "updated template name"
Would be great if you can add refute `template.name == "updated template name"`

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_controller_test.exs
> +      }
please remove variable declaration and assign the value directly as we are not using it second time

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_controller_test.exs
> +      }
please remove variable declaration and assign the value directly as we are not using it a second time

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_controller_test.exs
> +      assert Map.has_key?(response, "id")
It is not very clear whether the template is deleted or not. Please add test is the way we can say there was a template and after deletion that is no longer available.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_controller_test.exs
> +      }
please remove variable declaration and assign the value directly as we are not using it second time

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_controller_test.exs
> +      }
please remove variable declaration and assign the value directly as we are not using it a second time

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_controller_test.exs
> +      data = %{}
please remove variable declaration and assign the value directly

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_controller_test.exs
> +      response = conn |> json_response(400)
please remove single piping

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_controller_test.exs
> +      response = conn |> json_response(400)
better we can use like:

```
response = 
conn 
|> post(Routes.template_path(conn, :create, org.id), %{})
|> json_response(400)

```

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_instance_controller_test.exs
> +      }
Please remove the extra variable declaration.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_instance_controller_test.exs
> +      }
Please remove the extra variable declaration.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_instance_controller_test.exs
> +
Please remove the extra variable declaration.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_instance_controller_test.exs
> +      }
Please remove the extra variable declaration.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_instance_controller_test.exs
> +      assert Map.has_key?(response, "id")
Not very clear with test, please add specific to show the API request worked properly

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_instance_controller_test.exs
> +      }
Please remove the extra variable declaration.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_instance_controller_test.exs
> +      }
Please remove the extra variable declaration.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/template_instance_controller_test.exs
> +      response = conn |> json_response(400)
```suggestion
      response = 
        conn 
        |> post(Routes.template_instance_path(conn, :create, org.id), %{})
        |> json_response(400)
```

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/widget_instance_controller_test.exs
> +      }
Please remove the extra variable declaration.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/widget_instance_controller_test.exs
> +      }
Please remove the extra variable declaration.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/widget_instance_controller_test.exs
> +      assert response["label"] == "updated widget instance name"
Please add one more test to show that the old name is no longer available by matching widget_instance.label

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/widget_instance_controller_test.exs
> +      }
Please remove the extra variable declaration.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/widget_instance_controller_test.exs
> +      }
Please remove the extra variable declaration.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/widget_instance_controller_test.exs
> +      }
Please remove the extra variable declaration.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/widget_instance_controller_test.exs
> +      }
Please remove the extra variable declaration.

2022-01-19 06:37 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/reports/widget_instance_controller_test.exs
> +      response = conn |> json_response(400)
```suggestion
      response = 
        conn
        |> post(Routes.report_widget_path(conn, :create, org.id), %{})
        |> json_response(400)
```

2022-01-20 05:24 UTC, merged