fixes some warnings
DataKrewTech/MADS-IoT-Explorer pull request #250
Opened 2021-11-15 08:56 UTC by virusnitesh

This is the changes for basic warning fixes and to test the first commit

2021-11-15 08:56 UTC, virusnitesh commented
Will add more on this please verify this is the process we are following @arjun289 @Ayoush @BandanaPandey

2021-11-15 19:50 UTC, oyeb requested changes

2021-11-15 19:50 UTC, oyeb commented on config/dev.exs
> +  port: 5431,
Perhaps `port: System.get_env("LOCAL_DB_PORT", "5432")` to avoid breaking others' setup.

2021-11-16 18:34 UTC, oyeb commented on config/dev.exs
> +  port: 5431,
nvm, Arjun made this 5431 in #252.

2021-11-16 18:36 UTC, oyeb commented
@arjun289 The build for this PR passed. Is the ElasticSearch test failure sporadic? Or has it been fixed in this PR?

2021-12-23 00:06 UTC, merged