add user registration
DataKrewTech/MADS-IoT-Explorer pull request #259
Opened 2021-12-06 12:46 UTC by niteshcode4u

Jira: https://datakrew.atlassian.net/browse/MIP-290

2022-01-07 04:01 UTC, niteshcode4u commented
Jira: https://datakrew.atlassian.net/browse/MIP-290

2022-01-15 03:41 UTC, arjun289 requested changes
One thing which I have noticed is there is an authentication plug but no authorization plug for a user. It means the user token allows access to certain resources. I saw from the code that the user won't be able to access a certain resource as get_resource first tries to pull data from the shared_resource table and then returns the result. However, we have to be careful with that.

2022-01-15 03:41 UTC, arjun289 commented on apps/cockpit/config/dev.exs
> +      cd: Path.expand("../assets", __DIR__)
you can remove this block of code. We won't be using it.

2022-01-15 03:41 UTC, arjun289 commented on apps/cockpit/lib/cockpit/resource.ex
> +defmodule Cockpit.Resource do
I will suggest building modules by type of resources, this will help you isolate and then use apply() to choose between resources. This module should be used for dealing with requests common to all the resources.

2022-01-15 03:41 UTC, arjun289 commented on apps/cockpit/lib/cockpit/resource.ex
> +  defp convert_resource_type_to_code("reports"), do: 2
This should be an enum as I have previously mentioned. You should only be worried about resource type, assigning integers here is a bad idea.

2022-01-15 03:41 UTC, arjun289 commented on apps/cockpit/lib/cockpit_web/endpoint.ex
> +defmodule CockpitWeb.Endpoint do
Please check with @chandradot99 if there are socket requirements for the dashboard. Also, the design is a bit unclear on how it would be handled for the cockpit app.

2022-01-18 01:47 UTC, niteshcode4u commented on apps/cockpit/lib/cockpit_web/endpoint.ex
> +defmodule CockpitWeb.Endpoint do
Had a discussion with @chandradot99 and he told he doesn't need socket implementation in the cockpit

2022-01-18 01:55 UTC, niteshcode4u commented on apps/acqdat_core/lib/acqdat_core/cockpit/models/share_resource.ex
> +    |> from(where: sr.cockpit_user_id == ^cockpit_user_id, select: sr.org_id)
Won't occur issue as once we are getting a list of `org ids` (included duplicate as well) after this query then we are calling `Organisation.get_all_by_ids()` to get organization details where all the duplicated are handled.

2022-01-18 01:57 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api/resource_managment/share_resource.ex
> +    Enum.each(data.share_with, fn email ->
Didn't get this. why shall we get warnings?. here `data.share_with` will always have enumerables

2022-03-16 15:03 UTC, merged