Add subpanel CRUD APIs
DataKrewTech/MADS-IoT-Explorer pull request #260
Opened 2021-12-20 12:06 UTC by niteshcode4u

Jira: https://datakrew.atlassian.net/browse/MIP-314

2022-01-02 19:59 UTC, oyeb requested changes
I'm not comfortable with the duplication of the model. Since there is no logical distinction between panel and subpanel, there is no need for a subpanel model. Just adding `has_many` in addition to `belongs_to` should be enough.
It is my assumption that panels can potentially be nested ad infinitum (current schema/models suggest as much). @arjun289 do we need depth constraints?

Also, subpanels should be preloaded by GET `/panel/:id` endpoint.

The [linked JIRA ticket](https://datakrew.atlassian.net/browse/MIP-314) provides little value but its good that we have tests in this PR so reviewers can figure out what was intended.

2022-01-02 19:59 UTC, oyeb commented on apps/acqdat_core/lib/acqdat_core/dashboard_management/schema/panel.ex
> +    belongs_to(:parent, Panel, on_replace: :delete)
We should add the `has_many` relation to simplify our code. IMO, following is desirable:
1. panel cannot be created along with subpanels in a single query.
2. subpanels (`ps`) of panel (`p`) cannot be edited/deleted while editing `p`. The `children` key should never be `cast`ed.

However, if (1) is desired, then `children` key can be `cast`ed in `create_changeset` but not in `update_changeset` -- this will not conflict with (2).

```suggestion
    belongs_to(:parent, Panel, on_replace: :mark_as_invalid)  # prevents subpanels from auto-deletion. subpanels should be deleted explicitly even by raw changesets.
    has_many(:children, Panel)
```

This should help simplify queries and also reduce duplication, see other comments.

2022-01-02 19:59 UTC, oyeb commented on apps/acqdat_core/priv/repo/migrations/20211222042842_change_panel_table_to_self_referecing.exs
> +      add :parent_id, references(:acqdat_panel)
```suggestion
      add :parent_id, references(:acqdat_panel, on_delete: :delete_all)
```

2022-01-02 19:59 UTC, oyeb commented on apps/acqdat_api/lib/acqdat_api_web/controllers/dashboard_management/subpanel_controller.ex
> +  def update(conn, params) do
The frontend can simply short circuit by sending the update to `/panel/:id` instead of (`/panel/:parent_id/subpanels`, `%{subpanel_id: <id>}`)

If this controller should exist at all, it should only offer `index` and `show`, since there is no logical difference between a panel and a subpanel.

2022-01-03 08:00 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api_web/controllers/dashboard_management/subpanel_controller.ex
> +  def update(conn, params) do
I totally agree with you @oyeb but to make things consistent for UI development we are keeping like this for subpanel CRUD operation.

2022-01-04 03:05 UTC, arjun289 reviewed
I think there is one issue with uniqueness constraint in the PR. So uniqueness for panels under the dashboard is there. However, uniqueness under a panel can only be done with a combination of `parent_id` and `name` which I did not see.

2022-01-04 04:04 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api/dashboard_management/subpanel.ex
> +      [] -> {:error, "No subpanel for this panel"}
I agree that would be the better approach however I tried to maintain consistency like panel & dashboard

2022-01-04 04:59 UTC, niteshcode4u commented
> I think there is one issue with uniqueness constraint in the PR. So uniqueness for panels under the dashboard is there. However, uniqueness under a panel can only be done with a combination of `parent_id` and `name` which I did not see.

Sorry, but I really don't understand what you want to add @arjun289. In case you want to add that a subpanel name should be unique under the panel then - there is no need to add new unique constraints for subpanel.
As this is a reference for the panel itself so unique-constraints for the panel will take care of all and inside the dashboard, it won't allow adding subpanels with the same names as panel or existing subpanels.

If you want to add something else then would you mind elaborating a little more on what we exactly have to achieve here?

2022-01-04 10:19 UTC, niteshcode4u commented
> > I think there is one issue with uniqueness constraint in the PR. So uniqueness for panels under the dashboard is there. However, uniqueness under a panel can only be done with a combination of `parent_id` and `name` which I did not see.
> 
> Sorry, but I really don't understand what you want to add @arjun289. In case you want to add that a subpanel name should be unique under the panel then - there is no need to add new unique constraints for subpanel. As this is a reference for the panel itself so unique-constraints for the panel will take care of all and inside the dashboard, it won't allow adding subpanels with the same names as panel or existing subpanels.
> 
> If you want to add something else then would you mind elaborating a little more on what we exactly have to achieve here?

Hello,
So here problem we found is a little weird while creating unique constraints for panel name:

_Problem_: As per current development we are having unique constraints based on `panel name and dashboard id`. which was causing the issue of naming the subpanel (_as the subpanel is self-reference for the panel itself so it was stoping us to create the same name which already exists with that dashboard_).

_Solution_: We found after discussion that we should use the default value for parent_id as (-1) and this will solve our problem to create a unique index with the combination of [dashboard id, panel name, parent id].

Thank you @BandanaPandey @arjun289 If you want to add something else please go ahead

2022-01-05 02:01 UTC, merged