MIP-270 MIP 198 read previous event and switch action implementation
DataKrewTech/MADS-IoT-Explorer pull request #275
Opened 2022-01-16 19:12 UTC by SagarKarwande

2022-01-16 19:48 UTC, oyeb requested changes

2022-01-16 19:48 UTC, oyeb commented on apps/acqdat_core/lib/acqdat_core/streams/schema/switch_predicate.ex
> +  @optional_params ~W(position)a
`position` is also required.

2022-01-16 19:48 UTC, oyeb commented on apps/acqdat_core/lib/acqdat_core/streams/schema/switch.ex
> +  defp changeset(action, params) do
Indeed, `predicates` can be `nil` or even `[]` because we always provide the `default` case internally.

2022-01-16 19:48 UTC, oyeb commented on apps/acqdat_core/lib/acqdat_core/streams/schema/switch_predicate.ex
> +    |> validate_length(:entity_ids, min: 1, message: "Please select atleast one entity.")
We could drop this requirement and treat both `nil` and `[]` as the wildcard selection.

2022-01-18 05:18 UTC, SagarKarwande commented on apps/acqdat_core/lib/acqdat_core/streams/schema/switch.ex
> +  defp changeset(action, params) do
With current implementation they can be set as [].

2022-01-18 11:31 UTC, SagarKarwande commented on apps/acqdat_core/lib/acqdat_core/streams/schema/switch.ex
> +    embeds_many(:predicates, SwitchPredicate, on_replace: :delete)
Yes. Adding label field to the predicate.

We can structure the predicates a we want during pipeline executions

2022-01-18 11:44 UTC, SagarKarwande commented on apps/acqdat_core/lib/acqdat_core/streams/schema/switch_predicate.ex
> +    |> validate_length(:entity_ids, min: 1, message: "Please select atleast one entity.")
@oyeb When we have type of array then we cannot set it as nil.
Allowing to set [] instead.

2022-01-18 11:49 UTC, SagarKarwande commented on apps/acqdat_core/lib/acqdat_core/streams/schema/switch.ex
> +    embeds_many(:predicates, SwitchPredicate, on_replace: :delete)
Keeping entity_ids as optional now and setting it to default [].

2022-01-18 20:28 UTC, oyeb commented on apps/acqdat_core/lib/acqdat_core/streams/schema/switch.ex
> +    embeds_many(:predicates, SwitchPredicate, on_replace: :delete)
Yes, 1 label only... I meant to keep the predicates in an array instead of a map.

2022-01-18 20:39 UTC, oyeb approved these changes
lgtm now👍🏽

2022-01-18 20:42 UTC, merged