Feature/dashboard duplication
DataKrewTech/MADS-IoT-Explorer pull request #287
Opened 2022-01-27 08:17 UTC by natesh-chidhambaram

Implemented dashboard duplication functionality.
[MIP-324](https://datakrew.atlassian.net/browse/MIP-324)

2022-01-27 08:47 UTC, niteshcode4u requested changes

2022-01-27 08:47 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api/dashboard_management/dashboard.ex
> +      end
Let's use with clause and remove nested case structure

2022-01-27 08:47 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api/dashboard_management/dashboard.ex
> +                {:error, Reason}
typo: `Reason` variable should be named with lower case `reason`

2022-01-27 08:47 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api/dashboard_management/dashboard.ex
> +          {:error, Reason}
typo: `Reason` variable should be named with lower case `reason`

2022-01-27 08:47 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api_web/controllers/dashboard_management/dashboard_controller.ex
> +          |> Map.put_new("creator_id", String.to_integer(Guardian.Plug.current_resource(conn)))
please remove single piping

2022-01-27 08:47 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api_web/controllers/dashboard_management/dashboard_controller.ex
> +
please remove single piping

2022-01-27 08:47 UTC, niteshcode4u commented on apps/acqdat_api/lib/acqdat_api_web/controllers/dashboard_management/dashboard_controller.ex
> +        |> send_error(401, DashboardErrorHelper.error_message(:unauthorized))
please remove single piping

2022-01-27 08:47 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/dashboard-management/dashboard_controller_test.exs
> +        |> put_req_header("authorization", "Bearer #{bad_access_token}")
please remove single piping

2022-01-27 08:47 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/dashboard-management/dashboard_controller_test.exs
> +      result = conn |> json_response(403)
please remove single piping

2022-01-27 08:47 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/dashboard-management/dashboard_controller_test.exs
> +      response = conn |> json_response(400)
please remove single piping

2022-01-27 08:47 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/dashboard-management/dashboard_controller_test.exs
> +      response = conn |> json_response(200)
please remove single piping

2022-01-27 08:47 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/dashboard-management/dashboard_controller_test.exs
> +      query = from(s in Panel, where: s.dashboard_id == ^new_id)
`s in Panel` should be `p in Panel`

2022-01-27 08:47 UTC, niteshcode4u commented on apps/acqdat_api/test/acqdat_api_web/controllers/dashboard-management/dashboard_controller_test.exs
> +      db_resp = Repo.all(query)
```suggestion
     db_resp = 
       (p in Panel)
       |> from(where: p.dashboard_id == ^new_id)
       |> Repo.all()
```

2022-01-27 12:37 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api/dashboard_management/dashboard.ex
> +      settings: (dashboard.settings && Map.from_struct(dashboard.settings)) || %{},
@natesh-chidhambaram why settings key is duplicated here ?

2022-01-27 12:37 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api/dashboard_management/dashboard.ex
> +    datetime = DateTime.truncate(DateTime.utc_now(), :second)
@natesh-chidhambaram  where are you using this datetime var ?

2022-01-27 12:37 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api/dashboard_management/dashboard.ex
> +    datetime = DateTime.truncate(DateTime.utc_now(), :second)
same, where are we using this datetime ?

2022-01-27 12:37 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api_web/router.ex
> +        # post "/duplicate_dashboards", DashboardController, :duplicate_dashboard
@natesh-chidhambaram  please remove commented code

2022-01-27 12:37 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api_web/router.ex
> +          post "/duplicate_dashboards", DashboardController, :duplicate_dashboard
@natesh-chidhambaram  also make it plural duplicate_dashboard should be duplicate_dashboards

2022-01-27 13:28 UTC, natesh-chidhambaram commented on apps/acqdat_api/lib/acqdat_api/dashboard_management/dashboard.ex
> +    datetime = DateTime.truncate(DateTime.utc_now(), :second)
We are using the datetime in inserted_at and updated_at fields.

2022-01-28 04:30 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api/dashboard_management/dashboard.ex
> +    datetime = DateTime.truncate(DateTime.utc_now(), :second)
ok

2022-02-06 07:41 UTC, merged