Reports App fixes and refactoring
DataKrewTech/MADS-IoT-Explorer pull request #297
Opened 2022-03-03 08:29 UTC by dhavalarora

2022-03-09 12:49 UTC, BandanaPandey requested changes

2022-03-09 12:49 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api_web/controllers/dashboard_management/dashboard_controller.ex
> -  def reports(conn, params) do
@dhavalarora  why did you remove reports action from here, this particular feature is getting used on dashboard to download the reports ?
It is different than our reports app

2022-03-09 12:49 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api_web/controllers/dashboard_management/dashboard_export_controller.ex
> -  def reports(conn, params) do
here also @dhavalarora  why did you remove reports action from here, this particular feature is getting used to download the reports ?

2022-03-09 12:49 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api_web/controllers/reports/template_controller.ex
> +         templates <- TemplateModel.get_all(data) do
@dhavalarora  we don't directly use model functions here in controller, we use it through the context AcqdatApi.Reports.Template specified here (as def delegate).
Please make sure to no use model functions directly here, we follow this convention throughout our applications

2022-03-09 12:49 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api_web/controllers/reports/template_instance_controller.ex
> +         template_instances <- TemplateInstanceModel.get_all(data) do
Please don't call model functions directly, define in this file AcqdatApi.Reports.TemplateInstance
and then use it through it

2022-03-09 12:52 UTC, chandradot99 commented on apps/acqdat_api/lib/acqdat_api_web/controllers/dashboard_management/dashboard_controller.ex
> -  def reports(conn, params) do
@BandanaPandey we are moving download report feature from dashboard app and moving it to reports app.

2022-03-09 12:53 UTC, chandradot99 commented on apps/acqdat_api/lib/acqdat_api_web/controllers/dashboard_management/dashboard_export_controller.ex
> -  def reports(conn, params) do
@BandanaPandey same here also, we don't need this.

2022-03-10 07:26 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api_web/controllers/dashboard_management/dashboard_controller.ex
> -  def reports(conn, params) do
ok @chandradot99

2022-03-10 07:26 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api_web/controllers/dashboard_management/dashboard_export_controller.ex
> -  def reports(conn, params) do
ok @chandradot99

2022-03-10 07:28 UTC, BandanaPandey approved these changes

2022-03-15 14:52 UTC, merged