SMS Notification support for alerts using Twillio
DataKrewTech/MADS-IoT-Explorer pull request #329
Opened 2022-04-29 12:21 UTC by SagarKarwande

- SMS based support for alerts app

2022-05-02 06:30 UTC, BandanaPandey requested changes

2022-05-02 06:30 UTC, BandanaPandey commented on apps/notifications/lib/notifications.ex
> +    twilio_no = mqtt_port = System.fetch_env!("TWILIO_NUMBER")
@SagarKarwande Where are we using mqtt_port ?

2022-05-02 06:30 UTC, BandanaPandey commented on apps/notifications/lib/notifications.ex
> +    An alert has been generated in your MADS workspace on #{alert.inserted_timestamp}.
@SagarKarwande  here shouldn't we be using `inserted_at` instead of inserted_timestamp ?
Thoughts ?

2022-05-02 07:19 UTC, SagarKarwande commented on apps/notifications/lib/notifications.ex
> +    twilio_no = mqtt_port = System.fetch_env!("TWILIO_NUMBER")
it is a typo

2022-05-10 04:30 UTC, SagarKarwande commented on apps/notifications/lib/notifications.ex
> +    twilio_no = mqtt_port = System.fetch_env!("TWILIO_NUMBER")
It is fixed

2022-05-10 10:35 UTC, BandanaPandey commented on apps/notifications/lib/notifications.ex
> +    #{alert.message}
@SagarKarwande  Can we make it conditional,
If alert.message is present than only show it, else not show it ?

2022-05-10 11:45 UTC, BandanaPandey approved these changes

2022-05-10 13:45 UTC, merged