changes for widget_layout and web socket
DataKrewTech/MADS-IoT-Explorer pull request #336
Opened 2022-05-16 06:39 UTC by Ansvas

Changes for dashboard revamp.

2022-05-17 12:21 UTC, BandanaPandey requested changes

2022-05-17 12:21 UTC, BandanaPandey commented on apps/acqdat_api/lib/acqdat_api/dashboard_management/widget_instance.ex
> +  defp update_widget_broadcast_to_channel(data, %{panel_id: panel_id}) do
refactor update create and delete widget_broadcast_to_channel function
@Ansvas

2022-05-17 13:27 UTC, Ansvas commented on apps/acqdat_api/lib/acqdat_api_web/controllers/dashboard_management/panel_controller.ex
> +
create a seperate function for this

2022-05-17 13:33 UTC, Ansvas commented on apps/acqdat_core/lib/acqdat_core/tasks/update_widget_layout.ex
> +end
put it in the seed/dashboard file, refector if possible.

2022-05-30 10:27 UTC, BandanaPandey approved these changes

2022-06-03 03:47 UTC, merged